### PR TITLE
Updates to copy and adding a gif to signup flow

### PR DESCRIPTION
**Pull request by kelseyah**
I sort of made up the gif part 🙃

### CODE REVIEW

**Comment by kelseyah** [comment]
Yea I was actually wondering about those, but they were already set up that way so I'd defer to @mhfowler or @oshoham on the string combos.

@jayres I wasn't able to get my local environment fully setup so I have no idea if the attachment with the string works, but would it make more sense to do:

`      return Promise.all([geocodingResult, botReply(user, {
          attachment: {
            type: 'image',
            payload: {
              url: 'https://storage.googleapis.com/callparty/tada.gif'
            }
          }
        } )])
       .then(() => botReply(user, `Great, thanks!`))
    })
`

**Comment by mhfowler** [comment]
about to pull this down and test it out

**Comment by mhfowler** [comment]
put in a couple fixes to the singupConvo 

and snuck in a change to make captureException  use await 

@jayres I was using + between strings to avoid having newlines in the strings 
but @oshoham just showed me I can use this thing https://github.com/declandewet/common-tags#oneline

i'll change those strings in singupConvo to use that

**Comment by mhfowler** [comment]
oh nice line continuation seems better http://stackoverflow.com/questions/37321047/wrap-long-template-literal-line-to-multiline-without-creating-a-new-line-in-the

the thing I dont like about oneLine is it means you have to have a whitespace at the end of each line of string... but theres  also no way to see that its there

**Comment by mhfowler** [comment]
ah  nvmmmmmm

oneLine works well

(it seems to turn the newline into a space, or the indent on the line or something into space.. so no need to worry about invisible spaces)

**Pull request merged**
